language: ruby
addons:
  codeclimate:
    repo_token: 22840649ef0d6a85c80f7276acbb377b5baee4938f1d15741f34627245c84c92
env: RAILS_ENV=test
  - 'RAILS_VERSION=3.2.21'
  - 'RAILS_VERSION=4.2.6'
  - 'RAILS_VERSION=5.0.1'
rvm:
  - 2.3.1
  - 1.9.3
matrix:
  exclude:
  - rvm: 1.9.3
    env: 'RAILS_VERSION=4.2.6'
  - rvm: 1.9.3
    env: 'RAILS_VERSION=5.0.1'
  - rvm: 2.3.1
    env: 'RAILS_VERSION=3.2.21'
script:
  - bundle exec rails db:drop db:create db:migrate
  - bundle exec rspec
notifications:
  email:
    on_success: never
    on_failure: change
    recipients: programmers@admin.umass.edu
